title: Elon Gliksberg
email: elongliks@gmail.com
description: "I like solving problems and taking on challenges."
baseurl: ""
url: "https://elongl.github.io"
twitter_username: elongli
github_username: elongl

theme: minima
plugins:
  - jekyll-feed

google_analytics: UA-187846960-1
